### ISSUE TITLE
好像无法生成,报错Invalid combination of format, subtype and endian

### ISSUE THREAD

**Issue by cmdhb** [SlightDust/HuoZiYinShua_HoshinoBot#1]
[2024-01-15 10:51:38,248 nonebot] INFO: Message -1247439976 is ignored: Handled by Hoshino
[2024-01-15 10:51:38,248] ERROR in msghandler: Invalid combination of format, subtype and endian
Traceback (most recent call last):
  File "/root/pcrbot/HoshinoBot/hoshino/msghandler.py", line 28, in handle_message
    await service_func.func(bot, event)
  File "/root/pcrbot/HoshinoBot/hoshino/modules/HuoZiYinShua_HoshinoBot/otto.py", line 45, in ottohzys
    b64audio = HZYS.export(txt,inYsddMode=True,reverse=reverse)
  File "/root/pcrbot/HoshinoBot/hoshino/modules/HuoZiYinShua_HoshinoBot/HuoZiYinShua/huoZiYinShua.py", line 138, in export
    base64_data = base64.b64encode(self.__export().getvalue())
  File "/root/pcrbot/HoshinoBot/hoshino/modules/HuoZiYinShua_HoshinoBot/HuoZiYinShua/huoZiYinShua.py", line 253, in __export
    sf.write(bytesout, self.__concatenated, _targetSR, format="MP3")
  File "/usr/local/lib/python3.8/dist-packages/soundfile.py", line 343, in write
    with SoundFile(file, 'w', samplerate, channels,
  File "/usr/local/lib/python3.8/dist-packages/soundfile.py", line 656, in __init__
    self._info = _create_info_struct(file, mode, samplerate, channels,
  File "/usr/local/lib/python3.8/dist-packages/soundfile.py", line 1479, in _create_info_struct
    info.format = _format_int(format, subtype, endian)
  File "/usr/local/lib/python3.8/dist-packages/soundfile.py", line 1437, in _format_int
    raise ValueError(
ValueError: Invalid combination of format, subtype and endian

**Comment by SlightDust** [comment]
我这边一直没问题，还有什么复现条件吗，比如文字是什么，soundfile版本
